# This workflow sets up and runs MSBuild and VSTest
# to build and test a Visual Studio solution.

name: Build and Unit Test for C#

on:
  push:
    branches: 
      - main
      - development
  
  pull_request:
    branches:
      - main
      - development

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild and dotnet test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
    # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1
        id: setup_msbuild

       # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test

